### ISSUE TITLE
Request to list access plans results in fatal error

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#234]
### Reproduction Steps

+ Make a request go `GET /llms/v1/access-plans`

### Expected Behavior

+ Receive a list of access plans

### Actual Behavior

+ Fatal error encountered, see error below

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->
[17-Sep-2021 18:43:18 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::get() in /shared/httpd/llms/htdocs/wp-content/plugins/lifterlms-rest/includes/server/class-llms-rest-access-plans-controller.php:735
Stack trace:
#0 /shared/httpd/llms/htdocs/wp-content/plugins/lifterlms-rest/includes/server/class-llms-rest-access-plans-controller.php(152): LLMS_REST_Access_Plans_Controller->block_request_when_access_plan_limit_reached(Object(WP_REST_Request))
#1 /shared/httpd/llms/htdocs/wp-includes/rest-api.php(781): LLMS_REST_Access_Plans_Controller->create_item_permissions_check(Object(WP_REST_Request))
#2 /shared/httpd/llms/htdocs/wp-includes/class-wp-hook.php(303): rest_send_allow_header(Object(WP_REST_Response), Object(WP_REST_Server), Object(WP_REST_Request))
#3 /shared/httpd/llms/htdocs/wp-includes/plugin.php(189): WP_Hook->apply_filters(Object(WP_REST_Response), Array)
#4 /shared/httpd/llms/htdocs/wp-includes/rest-api/class-wp-rest-server.php(437): apply_filters('rest_post_dispa...', Object(WP_REST_Response), Object(WP_REST_Server), Object(WP_REST_Request))
#5 /shared/httpd/llms/htdocs/wp-includes/rest-api.php(370): WP_REST_Server->serve_request('/llms/v1/access...')
#6 /shared/httpd/llms/htdocs/wp-includes/class-wp-hook.php(303): rest_api_loaded(Object(WP))
#7 /shared/httpd/llms/htdocs/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#8 /shared/httpd/llms/htdocs/wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#9 /shared/httpd/llms/htdocs/wp-includes/class-wp.php(388): do_action_ref_array('parse_request', Array)
#10 /shared/httpd/llms/htdocs/wp-includes/class-wp.php(750): WP->parse_request('')
#11 /shared/httpd/llms/htdocs/wp-includes/functions.php(1291): WP->main('')
#12 /shared/httpd/llms/htdocs/wp-blog-header.php(16): wp()
#13 /shared/httpd/llms/htdocs/index.php(17): require('/shared/httpd/l...')
#14 {main}
  thrown in /shared/httpd/llms/htdocs/wp-content/plugins/lifterlms-rest/includes/server/class-llms-rest-access-plans-controller.php on line 735
```

### System Information

<details>
<summary>System Report</summary>
  
```
<!-- Paste your System Report below this line -->

```

</details>

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
@thomasplevy I think this is something weird of WordPress.
Here: #2 /shared/httpd/llms/htdocs/wp-includes/class-wp-hook.php(303): rest_send_allow_header(Object(WP_REST_Response), Object(WP_REST_Server), Object(WP_REST_Request))

all the permissions callbacks related to an endpoint+method are checked https://developer.wordpress.org/reference/functions/rest_send_allow_header/

And, in the method that fails, since I call it in callbacks that I thought were executed only to check creation/update I always took for granted that either the resource `id` (update) or the `post_id` (create) were defined.
